import './styles.css';
import { NAV_ITEMS, WORKFLOWS } from './config.js';
import { getSession, signIn, signOut } from './services/auth.js';
import { createJob, getProfile, listJobs, setJobStatus } from './services/jobs.js';
import { isSupabaseConfigured } from './services/supabase.js';

const app = document.querySelector('#app');
const state = { session: null, profile: null, page: 'board', jobs: [], selectedId: null, error: '' };
const names = { incoming:'Incoming', queued:'Queued', printing:'Printing', drying:'Drying', contour_cutting:'Contour Cutting', weeding:'Weeding', heat_press:'Heat Press', quality_check:'Quality Check', ready:'Ready', collected:'Collected' };
const statuses = Object.keys(names).filter((key) => key !== 'collected');
const icon = (name) => ({ board:'▦', 'new-job':'+', 'my-jobs':'◷', stock:'◫', settings:'⚙' }[name]);
const esc = (value = '') => String(value).replace(/[&<>'"]/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c]));
const production = () => state.profile?.role === 'production';
const jobNo = (job) => `PN-${new Date(job.created_at).getFullYear()}-${String(job.job_number).padStart(5, '0')}`;
const next = (job) => {
  if (job.status === 'incoming') return 'queued';
  const steps = WORKFLOWS[job.job_type]; const index = steps.indexOf(names[job.status]);
  return index < steps.length - 1 ? Object.keys(names).find((key) => names[key] === steps[index + 1]) : job.status === 'ready' ? 'collected' : null;
};
async function refresh() { try { state.profile = await getProfile(state.session.user.id); state.jobs = await listJobs(); state.error = ''; } catch (error) { state.error = error.message; } render(); }

function card(job) { const nextStep = next(job); return `<article class="job-card ${job.priority}"><div class="job-card__top"><span class="job-id">${jobNo(job)}</span><span class="priority">${job.priority}</span></div><h3>${esc(job.customer_name)}</h3><p class="branch">${esc(job.branch)} · ${job.job_type === 'flex' ? 'T-shirt Flex' : 'Stickers'}</p><dl><div><dt>Material</dt><dd>${esc(job.material)}</dd></div><div><dt>Specification</dt><dd>${esc(job.specification)} · ${job.quantity}</dd></div></dl><div class="job-card__next"><span>Next</span><strong>${nextStep ? names[nextStep] : 'Complete'}</strong></div><button class="button" data-open-job="${job.id}">View job</button></article>`; }
function board() { const active = state.jobs.filter((job) => job.status !== 'collected'); return `<section class="page-heading"><div><p class="eyebrow">${production() ? 'Production centre' : esc(state.profile?.branch)}</p><h1>Production Board</h1><p>Live jobs from intake through to collection.</p></div><button class="button button--primary" data-page="new-job">+ New job</button></section>${state.error ? `<p class="form-error">${esc(state.error)}</p>` : ''}<section class="overview"><article><span>Active jobs</span><strong>${active.length}</strong><small>Across all production stages</small></article><article><span>Urgent</span><strong>${active.filter((job) => job.priority === 'urgent').length}</strong><small>Needs attention first</small></article><article><span>Ready today</span><strong>${active.filter((job) => job.status === 'ready').length}</strong><small>Awaiting collection</small></article><article class="machine"><span>Roland BN-20</span><strong><i></i> Ready</strong><small>Manual status for Sprint 2</small></article></section><section class="board">${statuses.map((status) => { const jobs = active.filter((job) => job.status === status); return `<div class="board-column"><header><h2>${names[status]}</h2><span>${jobs.length}</span></header><div class="job-list">${jobs.map(card).join('') || '<p class="empty">No jobs here</p>'}</div></div>`; }).join('')}</section>`; }
function materials(type) { return (type === 'flex' ? ['White Flex','Gold Flex','Silver Flex'] : ['Gloss Vinyl','Matte Vinyl','Clear Vinyl','Contravision']).map((value) => `<option>${value}</option>`).join(''); }
function newJob() { const branch = production() ? `<select name="branch">${['Plettenberg Bay','Knysna','Waterside','Sedgefield'].map((value) => `<option ${value === state.profile.branch ? 'selected' : ''}>${value}</option>`).join('')}</select>` : `<input value="${esc(state.profile.branch)}" disabled><input type="hidden" name="branch" value="${esc(state.profile.branch)}">`; return `<section class="page-heading"><div><p class="eyebrow">Production intake</p><h1>New Job</h1><p>Artwork stays in email; this records production requirements.</p></div></section><form class="job-form" id="job-form"><fieldset><legend>Job details</legend><label>Branch${branch}</label><label>Customer name<input name="customer" required></label><label>Priority<select name="priority"><option value="standard">Standard</option><option value="rush">Rush</option><option value="urgent">Urgent</option></select></label><label>Email subject / reference<input name="emailReference" required placeholder="RE: Sticker order — Ocean Blue"></label></fieldset><fieldset><legend>Production requirements</legend><label>Job type<select name="type" id="job-type"><option value="stickers">Stickers</option><option value="flex">T-shirt Flex</option></select></label><label>Material<select name="material" id="material">${materials('stickers')}</select></label><label>Size / placement<input name="specification" required placeholder="90 × 50 mm or front chest"></label><label>Quantity<input name="quantity" type="number" min="1" required></label></fieldset><fieldset><legend>Artwork checklist</legend><label class="check"><input required type="checkbox"> PDF or CDR received by email</label><label class="check"><input required type="checkbox"> Artwork is print-ready and correct size</label><label class="check"><input required type="checkbox"> Customer approved artwork</label><label class="check"><input name="cutlines" type="checkbox"> Cutlines included</label></fieldset><p class="form-error"></p><div class="form-actions"><button class="button button--primary">Submit to incoming jobs</button></div></form>`; }
function details() { const job = state.jobs.find((item) => item.id === state.selectedId); if (!job) return board(); const upcoming = next(job); return `<section class="page-heading"><div><button class="button" data-page="board">← Back to board</button><p class="eyebrow">${jobNo(job)} · ${names[job.status]}</p><h1>${esc(job.customer_name)}</h1><p>${esc(job.branch)} · ${job.job_type === 'flex' ? 'T-shirt Flex' : 'Stickers'}</p></div>${production() && upcoming ? `<button class="button button--primary" data-advance="${job.id}">${job.status === 'incoming' ? 'Accept into queue' : `Move to ${names[upcoming]}`}</button>` : ''}</section><section class="job-form"><fieldset><legend>Production requirements</legend><label>Material<input value="${esc(job.material)}" disabled></label><label>Specification<input value="${esc(job.specification)} · ${job.quantity}" disabled></label><label>Priority<input value="${esc(job.priority)}" disabled></label><label>Email reference<input value="${esc(job.email_reference)}" disabled></label></fieldset><fieldset><legend>Artwork confirmation</legend><label class="check"><input checked disabled type="checkbox"> Print-ready artwork confirmed</label><label class="check"><input ${job.cutlines_included ? 'checked' : ''} disabled type="checkbox"> Cutlines included</label></fieldset></section>`; }
function simple(title) { return `<section class="page-heading"><div><p class="eyebrow">Coming later</p><h1>${title}</h1><p>This module arrives in a later sprint.</p></div></section>`; }
function shell(view) { const nav = NAV_ITEMS.map(([id,label]) => `<button class="nav-item ${state.page === id ? 'active' : ''}" data-page="${id}"><span>${icon(id)}</span>${label}</button>`).join(''); return `<div class="app-shell"><aside class="sidebar"><a class="brand"><span>PN</span><b>PostNet<br>Production</b></a><nav>${nav}</nav><div class="sidebar-footer"><small>${production() ? 'Production Centre' : 'Branch'}</small><strong>${esc(state.profile?.branch)}</strong></div></aside><main><header class="topbar"><div class="connection connected"><i></i>Live database</div><div class="user-menu"><span>${state.session.user.email.slice(0,1).toUpperCase()}</span><button data-signout>Sign out</button></div></header><div class="content">${view}</div></main></div>`; }
function login() { return `<main class="login"><section><a class="brand brand--dark"><span>PN</span><b>PostNet<br>Production</b></a><p class="eyebrow">Production workflow management</p><h1>Welcome back</h1><p>Sign in to manage work across the production centre and branches.</p><form id="login-form"><label>Work email<input name="email" type="email" required></label><label>Password<input name="password" type="password" required></label><p class="form-error"></p><button class="button button--primary" ${isSupabaseConfigured ? '' : 'disabled'}>Sign in</button></form></section><aside><p>Built for the production centre.</p><h2>Know the next job, its exact requirements, and where every other job is in the process.</h2></aside></main>`; }
function render() { if (!state.session) { app.innerHTML = login(); return; } const views = {board, 'new-job':newJob, 'job-details':details, 'my-jobs':() => `<section class="page-heading"><div><p class="eyebrow">Job history</p><h1>My Jobs</h1></div></section><section class="job-table">${state.jobs.map(card).join('') || '<p>No jobs yet.</p>'}</section>`, stock:() => simple('Stock'), settings:() => simple('Settings')}; app.innerHTML = shell(views[state.page]()); }
app.addEventListener('click', async (event) => { const page = event.target.closest('[data-page]')?.dataset.page; if (page) { state.page = page; render(); } const open = event.target.closest('[data-open-job]'); if (open) { state.selectedId = open.dataset.openJob; state.page = 'job-details'; render(); } if (event.target.closest('[data-signout]')) { await signOut(); state.session = null; state.profile = null; state.jobs = []; render(); } const advance = event.target.closest('[data-advance]'); if (advance) { const job = state.jobs.find((item) => item.id === advance.dataset.advance); try { const saved = await setJobStatus(job.id, next(job), job.status === 'incoming' ? state.session.user.id : null); state.jobs = state.jobs.map((item) => item.id === saved.id ? saved : item); render(); } catch (error) { state.error = error.message; render(); } } });
app.addEventListener('change', (event) => { if (event.target.id === 'job-type') document.querySelector('#material').innerHTML = materials(event.target.value); });
app.addEventListener('submit', async (event) => { event.preventDefault(); if (event.target.id === 'login-form') { const form = new FormData(event.target); const message = event.target.querySelector('.form-error'); try { await signIn(form.get('email'), form.get('password')); state.session = await getSession(); await refresh(); } catch (error) { message.textContent = error.message; } } if (event.target.id === 'job-form') { const form = new FormData(event.target); const message = event.target.querySelector('.form-error'); try { const job = await createJob({branch:form.get('branch'), customer_name:form.get('customer'), email_reference:form.get('emailReference'), job_type:form.get('type'), material:form.get('material'), specification:form.get('specification'), quantity:Number(form.get('quantity')), priority:form.get('priority'), cutlines_included:form.get('cutlines') === 'on', artwork_checklist_complete:true, created_by:state.session.user.id}); state.jobs.unshift(job); state.selectedId = job.id; state.page = 'job-details'; render(); } catch (error) { message.textContent = error.message; } } });
state.session = await getSession(); if (state.session) await refresh(); else render();
